name: Tag Workflow

on:
  push:
    tags:
      - 'r*'  # Déclenchement pour les tags commençant par 'r' ok

jobs:
  tagged_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

  job1:
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Affiche VAR1
            run: |
                  echo "La valeur de la variable est ${{ vars.VAR1 }}"
  job2:
          needs: job1
          if : failure()
          runs-on : ubuntu-latest
          steps:
            - name: Affiche que le Job1 a echoue
              run: echo "Job1 a echoue"
      